tags:
  - name: Serie
    description: The serie's managing API

paths:
  /series/all:
    get:
      summary: Retrieve serie's list
      tags: [Serie]
      responses:
        200:
          description: The series' list.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Serie'
        500:
          description: Internal server error
  /series/{id}:
    get:
      summary: Retrieve one serie
      tags: [Serie]
      responses:
        200:
          description: The requested serie.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Serie'
        500:
          description: Internal server error
  /series/genre/{genre_id}:
    get:
      summary: Retrieve series by genre
      tags: [Serie]
      responses:
        200:
          description: A list of series sort by genre.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Serie'
        500:
          description: Internal server error

components:
  schemas:
    Serie:
      type: object
      properties:
        id:
          type: number
          description: The auto-generated id of a serie
        title:
          type: string
          description: The title of the serie
        duration:
          type: time
          description: The duration of a serie
        release_date:
          type: number
          description: The year the serie was released
        summary:
          type: string
          description: The summary of a serie
        director_id:
          type: number
          description: The auto-generated id of a director
        genre_id:
          type: number
          description: The auto_generated id of a genre
        pegi:
          type: number
          description: The age limit to see a serie
        trailer:
          type: string
          description: A YouTube link to the trailer of a serie
        poster:
          type: string
          description: A link to the poster of a serie
      example:
        id: 1
        title: Breaking Bad
        duration: 00:49:00
        release_date: 2008
        summary: A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine to secure his family's future.
        director_id: 2
        genre_id: 11
        pegi: 17
        trailer: https://www.youtube.com/watch?v=ceqOTZnhgY8
        poster: https://m.media-amazon.com/images/M/MV5BYmQ4YWMxYjUtNjZmYi00MDQ1LWFjMjMtNjA5ZDdiYjdiODU5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg
