tags:
  name: Register
  description: The register managing API

# --- Routes
paths:
  /register:
    post:
      summary: Create a new user account
      tags: [Register]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User's username
                email:
                  type: string
                  format: email
                  description: User's email
                password:
                  type: string
                  format: password
                  description: User's password
              required:
                - username
                - email
                - password
      responses:
        200:
          description: User's account is created
          items:
          $ref: '#/components/schemas/Register'
        400:
          description: Incorrect data
        500:
          description: Internal server error

# --- Types
components:
  schemas:
    Register:
      type: object
      properties:
        id:
          type: number
          description: The auto-generated id of a user
        username:
          type: string
          description: The chosen username
        email:
          type: string
          description: The user's email
        password:
          type: string
          description: The user's password
      example:
        id: 1
        username: Wtfluna
        email: adeline.merle@gmail.com
        password: pass123
